FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD mle-se.jar /opt/mle-se/
EXPOSE 8080
WORKDIR /opt/mle-se/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "mle-se.jar"]
